mode:
    mode: 'train'
    model_zoo: 'controlnet'
    multiprocessing_distributed: False
    dist_url: tcp://127.0.0.1:2345
    num_threads: 1
    do_online_eval: True
    parameter_path: ''
train:
    dim_x: 10
    dim_z: ''
    dim_a: 10
    dim_gt: 10
    num_ensemble: 32
    win_size: 24
    seed: 0
    model_name: 'duck_controlnet'
    dataset: 'Duck'
    sensor_len: 2
    channel_img_1: 3
    channel_img_2: ''
    input_size_1: 77
    input_size_2: ''
    input_size_3: ''
    data_path: [
        '/home/ssdArray/datasets/diff_control_data/pick_duck/pick_duck_1',
        '/home/ssdArray/datasets/diff_control_data/pick_duck/pick_duck_2'
    ]
    batch_size: 64
    num_epochs: 1000
    learning_rate: 1e-4
    weight_decay: 1e-6
    adam_eps: 1e-3
    log_freq: 10
    eval_freq: 100
    save_freq: 100
    log_directory: './experiments'
    loss: 'mse'
test:
    dim_x: 10
    dim_z: ''
    dim_a: 10
    dim_gt: 10
    num_ensemble: 32
    win_size: 24
    model_name: 'duck_controlnet'
    data_path: [
        '/home/ssdArray/datasets/diff_control_data/pick_duck/pick_duck_2'
    ]
    sensor_len: 2
    channel_img_1: 3
    channel_img_2: ''
    input_size_1: 77
    input_size_2: ''
    input_size_3: ''
    checkpoint_path_1: './experiments/duck_diffusion/v1.0-ema-model-19600'
    checkpoint_path_2: './experiments/duck_diffusion/v1.0-sensor_model-19600'
    dataset: 'Duck'
optim:
    optim: 'adamw'
    lr_scheduler: 'polynomial_decay'